return {
    Treasure = {
        ["Gold Coin"] = {},
        ["Fillionaire"] = {},
        ["Sunken Rod"] = {},
        ["Forsaken Shores Pond"] = {},
        ["Tempest Totem"] = {},
        ["Ancient Thread"] = {},
        ["Enchant Relic"] = {},
        ["Compass"] = {},
        ["Lunar Thread"] = {},
        ["Aurora Totem"] = {},
        ["Weird Algae"] = {},
        ["Quality Bait Crate"] = {},
        ["Meteor Totem"] = {},
        ["Forsaken Shores Ocean"] = {},
        ["Meteor Stone"] = {},
        ["Magic Thread"] = {},
        ["Whaley"] = {},
        ["Truffle Worm"] = {},
    },
    Rods = {
        ["Long Rod"] = { Price = "4500" },
        ["Developers Rod"] = { Price = "inf" },
        ["Frost Warden Rod"] = { Price = "inf" },
        ["Mystic Staff"] = { Price = "inf" },
        ["Fortune Rod"] = { Price = "12750" },
        ["Seasons Rod"] = { Price = "inf" },
        ["Riptide Rod"] = { Price = "inf" },
        ["Fischmas Rod"] = { Price = "inf" },
        ["Resourceful Rod"] = { Price = "inf" },
        ["Heaven's Rod"] = { Price = "1750000" },
        ["Summit Rod"] = { Price = "300000" },
        ["Midas Rod"] = { Price = "55000" },
        ["Precision Rod"] = { Price = "inf" },
        ["Steady Rod"] = { Price = "7000" },
        ["Rod Of The Depths"] = { Price = "750000" },
        ["Frostbane Rod"] = { Price = "inf" },
        ["Training Rod"] = { Price = "300" },
        ["Phoenix Rod"] = { Price = "40000" },
        ["Relic Rod"] = { Price = "inf" },
        ["Executive Rod"] = { Price = "inf" },
        ["Voyager Rod"] = { Price = "inf" },
        ["Fabulous Rod"] = { Price = "inf" },
        ["Avalanche Rod"] = { Price = "35000" },
        ["No-Life Rod"] = { Price = "inf" },
        ["Event Horizon Rod"] = { Price = "inf" },
        ["Test Rod"] = { Price = "inf" },
        ["Arctic Rod"] = { Price = "25000" },
        ["Plastic Rod"] = { Price = "900" },
        ["Magnet Rod"] = { Price = "15000" },
        ["Magma Rod"] = { Price = "inf" },
        ["Astral Rod"] = { Price = "inf" },
        ["Katana Rod"] = { Price = "inf" },
        ["Rapid Rod"] = { Price = "14000" },
        ["Flimsy Rod"] = { Price = "0" },
        ["Pen Rod"] = { Price = "inf" },
        ["The Lost Rod"] = { Price = "inf" },
        ["Fast Rod"] = { Price = "4500" },
        ["Crystalized Rod"] = { Price = "35000" },
        ["Firework Rod"] = { Price = "35000" },
        ["The Twig"] = { Price = "inf" },
        ["Rod Of The Exalted One"] = { Price = "inf" },
        ["Rod Of The Forgotten Fang"] = { Price = "inf" },
        ["Fischer's Rod"] = { Price = "inf" },
        ["UnRegistered"] = { Price = "No Price" },
        ["Wisdom Rod"] = { Price = "inf" },
        ["Scurvy Rod"] = { Price = "50000" },
        ["Mythical Rod"] = { Price = "110000" },
        ["Kings Rod"] = { Price = "120000" },
        ["Prismatic Rod"] = { Price = "inf" },
        ["Carbon Rod"] = { Price = "2000" },
        ["Aurora Rod"] = { Price = "90000" },
        ["Abyssal Spinecaster"] = { Price = "inf" },
        ["Lucky Rod"] = { Price = "5250" },
        ["Stone Rod"] = { Price = "3000" },
        ["Electric Guitar"] = { Price = "inf" },
        ["Antler Rod"] = { Price = "inf" },
        ["Destiny Rod"] = { Price = "190000" },
        ["Rex Umbrarum"] = { Price = "inf" },
        ["Nocturnal Rod"] = { Price = "11000" },
        ["Trident Rod"] = { Price = "150000" },
        ["Fungal Rod"] = { Price = "inf" },
        ["Haunted Rod"] = { Price = "inf" },
        ["Tetra Rod"] = { Price = "inf" },
        ["Candy Cane Rod"] = { Price = "inf" },
        ["Seraphic Rod"] = { Price = "inf" },
        ["Reinforced Rod"] = { Price = "20000" },
        ["Buddy Bond Rod"] = { Price = "inf" },
        ["Ultratech Rod"] = { Price = "inf" },
        ["Rod Of The Eternal King"] = { Price = "inf" },
        ["Sunken Rod"] = { Price = "inf" },
        ["Evil Pitchfork of Doom Rod"] = { Price = "inf" },
        ["Celestial Rod"] = { Price = "inf" },
        ["Krampus's Rod"] = { Price = "inf" },
        ["Ice Warpers Rod"] = { Price = "65000" },
        ["Frostfire Rod"] = { Price = "inf" },
        ["Sovereign Doombringer"] = { Price = "inf" },
        ["Auric Rod"] = { Price = "inf" },
        ["North-Star Rod"] = { Price = "inf" },
    },
    Enchants = {
        ["Sea King"] = { Description = "Makes fish 10% bigger", Color = "0.207843, 0.301961, 0.827451" },
        ["Lucky"] = { Description = "Increases luck by 20%", Color = "0.494118, 0.898039, 0.643137" },
        ["Clever"] = { Description = "2.25X XP after catching a fish", Color = "1, 0.431373, 0.65098" },
        ["Sea Overlord"] = { Description = "Makes fish 25% bigger", Color = "0.2, 0.658824, 0.827451" },
        ["Scrapper"] = { Description = "60% chance to not consume bait", Color = "1, 0.607843, 0.32549" },
        ["Divine"] = { Description = "Increases luck by 45%", Color = "0.776471, 0.898039, 0.862745" },
        ["Long"] = { Description = "Increases line distance by 50 studs", Color = "0.87451, 0.647059, 0.25098" },
        ["Swift"] = { Description = "Decreases lure time by 30%", Color = "0.709804, 0.890196, 0.898039" },
        ["Mystical"] = { Description = "Increased resilience by 45%", Color = "0.760784, 0.87451, 1" },
        ["Anomalous"] = { Description = "Caught fish have a 10% chance to be duplicated and Anomalous", Color = "1, 0.113725, 0.113725" },
        ["Immortal"] = { Description = "Increases luck by 75%", Color = "0.909804, 0.85098, 1" },
        ["Herculean"] = { Description = "Increases strength by 25,000kg", Color = "1, 0.917647, 0" },
        ["Noir"] = { Description = "Caught fish have a 50% chance to be Albino or Darkened.", Color = "1, 1, 1" },
        ["Controlled"] = { Description = "Increased rod control bar size", Color = "0.686275, 0.607843, 1" },
        ["Abyssal"] = { Description = "Caught fish have a 10% chance to be Abyssal.", Color = "0.152941, 0.223529, 0.678431" },
        ["Invincible"] = { Description = "Allows fishing in any body of liquid.", Color = "1, 0.384314, 0.0980392" },
        ["Wormhole"] = { Description = "45% chance to catch a fish from a random place", Color = "0.568627, 0.352941, 1" },
        ["Breezed"] = { Description = "Luck is increased by 65% during a windy day", Color = "0.737255, 0.815686, 1" },
        ["Quantum"] = { Description = "Caught fish have a 25% chance to be Subspace.", Color = "1, 0, 0.701961" },
        ["Blessed"] = { Description = "Increases shiny & sparkling chances by 2%", Color = "1, 0.309804, 0.643137" },
        ["Resilient"] = { Description = "Increased resilience by 35%", Color = "0.415686, 1, 0.776471" },
        ["Unbreakable"] = { Description = "Increases strength by 10,000kg", Color = "0.882353, 0.701961, 0.898039" },
        ["Insight"] = { Description = "1.5X XP after catching a fish", Color = "0.501961, 1, 0.447059" },
        ["Hasty"] = { Description = "Decreases lure time by 55%", Color = "0.898039, 0.819608, 0.360784" },
        ["Quality"] = { Description = "Increases luck by 15%, Resilience by 5%, and Lure Speed by 15%", Color = "0.619608, 1, 0.215686" },
        ["Piercing"] = { Description = "Rod has a chance to stab fish while reeling.", Color = "0.0509804, 0.654902, 0.552941" },
        ["Mutated"] = { Description = "Increases mutation luck by 7%", Color = "0.576471, 0.898039, 0.439216" },
        ["Storming"] = { Description = "Luck is increased by 95% during a rainy day", Color = "1, 0.92549, 0.513726" },
        ["Steady"] = { Description = "Reduces progress loss by 25% when fishing", Color = "0.898039, 0.811765, 0.74902" },
        ["Ghastly"] = { Description = "20% chance for a fish to be Translucent", Color = "0.505882, 0.87451, 0.678431" },
    },
    Items = {
        ["Windset Totem"] = { Price = "2000", Type = "Item" },
        ["Tidebreaker"] = { Price = "80000", Type = "Item" },
        ["Blizzard Totem"] = { Price = "275000", Type = "Item" },
        ["Magic Thread"] = { Price = "inf", Type = "Item" },
        ["Tempest Totem"] = { Price = "2000", Type = "Item" },
        ["Ancient Thread"] = { Price = "inf", Type = "Item" },
        ["Flippers"] = { Price = "9000", Type = "Item" },
        ["Red Energy Crystal"] = { Price = "0", Type = "Fish" },
        ["Lunar Thread"] = { Price = "inf", Type = "Item" },
        ["Aurora Totem"] = { Price = "500000", Type = "Item" },
        ["Basic Diving Gear"] = { Price = "3000", Type = "Item" },
        ["Beginner Oxygen Tank"] = { Price = "3500", Type = "Item" },
        ["Witches Ingredient"] = { Price = "10000", Type = "Item" },
        ["Firework"] = { Price = "130", Type = "Item" },
        ["Quality Bait Crate"] = { Price = "525", Type = "Fish" },
        ["Bait Crate"] = { Price = "120", Type = "Fish" },
        ["Avalanche Totem"] = { Price = "150000", Type = "Item" },
        ["Conception Conch"] = { Price = "444", Type = "Item" },
        ["Fillionaire"] = { Price = "inf", Type = "Item" },
        ["Volcanic Geode"] = { Price = "600", Type = "Fish" },
        ["Advanced Oxygen Tank"] = { Price = "25000", Type = "Item" },
        ["Winter Cloak"] = { Price = "7500", Type = "Item" },
        ["Nuke"] = { Price = "inf", Type = "Item" },
        ["Advanced Diving Gear"] = { Price = "15000", Type = "Item" },
        ["Common Crate"] = { Price = "128", Type = "Fish" },
        ["Festive Bait Crate"] = { Price = "1150", Type = "Fish" },
        ["Crab Cage"] = { Price = "45", Type = "Item" },
        ["Carbon Crate"] = { Price = "490", Type = "Fish" },
        ["Coral Geode"] = { Price = "600", Type = "Fish" },
        ["Smokescreen Totem"] = { Price = "2000", Type = "Item" },
        ["Eclipse Totem"] = { Price = "250000", Type = "Item" },
        ["Treasure Map"] = { Price = "inf", Type = "Item" },
        ["Basic Oxygen Tank"] = { Price = "1000", Type = "Item" },
        ["Fish Radar"] = { Price = "8000", Type = "Item" },
        ["Advanced Glider"] = { Price = "2500", Type = "Item" },
        ["Intermediate Oxygen Tank"] = { Price = "10000", Type = "Item" },
        ["Pickaxe"] = { Price = "5000", Type = "Item" },
        ["GPS"] = { Price = "100", Type = "Item" },
        ["Meteor Totem"] = { Price = "75000", Type = "Item" },
        ["Glider"] = { Price = "900", Type = "Item" },
        ["Sundial Totem"] = { Price = "2000", Type = "Item" },
        ["Super Flippers"] = { Price = "30000", Type = "Item" },
        ["Regular Token"] = { Price = "inf", Type = "Item" },
        ["Elite Token"] = { Price = "inf", Type = "Item" },
        ["Bag of Presents"] = { Price = "inf", Type = "Item" },
        ["Handwritten Note"] = { Price = "inf", Type = "Item" },
        ["Skin Crate"] = { Price = "inf", Type = "Item" },
    },
    Mutations = {
        ["Blessed"] = { PriceMultiply = "10", Color = "1, 0.901961, 0.411765", Chance = "0" },
        ["Subspace"] = { PriceMultiply = "5", Color = "1, 0, 0.784314", Chance = "0" },
        ["Silver"] = { PriceMultiply = "1.6", Color = "0.807843, 0.933333, 1", Chance = "15" },
        ["Mosaic"] = { PriceMultiply = "1.5", Color = "0.984314, 0.756863, 1", Chance = "10" },
        ["Jolly"] = { PriceMultiply = "1.2", Color = "0.0627451, 0.368627, 0.0745098", Chance = "0" },
        ["Celestial"] = { PriceMultiply = "2", Color = "1, 0.886275, 0.423529", Chance = "0" },
        ["Scorched"] = { PriceMultiply = "1.3", Color = "0.278431, 0.117647, 0.0666667", Chance = "9" },
        ["Fossilized"] = { PriceMultiply = "2.5", Color = "0.815686, 0.709804, 1", Chance = "4" },
        ["Albino"] = { PriceMultiply = "1.1", Color = "0.988235, 0.996078, 1", Chance = "30" },
        ["Abyssal"] = { PriceMultiply = "1", Color = "0.0470588, 0.0588235, 0.831373", Chance = "5" },
        ["Aurora"] = { PriceMultiply = "6.5", Color = "0.305882, 1, 0.85098", Chance = "0" },
        ["Darkened"] = { PriceMultiply = "1.3", Color = "0.227451, 0.239216, 0.243137", Chance = "30" },
        ["Blighted"] = { PriceMultiply = "3", Color = "0.415686, 0.313726, 0.811765", Chance = "0" },
        ["Aureate"] = { PriceMultiply = "4", Color = "0.54902, 0.243137, 0.027451", Chance = "0" },
        ["Firework"] = { PriceMultiply = "3.5", Color = "0.529412, 0.494118, 1", Chance = "0" },
        ["Frozen"] = { PriceMultiply = "1.3", Color = "0.513726, 1, 0.901961", Chance = "10" },
        ["Aurous"] = { PriceMultiply = "2", Color = "0.45098, 0.0392157, 0.0392157", Chance = "0" },
        ["Amber"] = { PriceMultiply = "0.5", Color = "1, 0.454902, 0.2", Chance = "8" },
        ["Mythical"] = { PriceMultiply = "4.5", Color = "1, 0.321569, 0.580392", Chance = "1" },
        ["Anomalous"] = { PriceMultiply = "2.5", Color = "1, 0.168627, 0.168627", Chance = "0" },
        ["Sandy"] = { PriceMultiply = "1.2", Color = "1, 0.764706, 0.631373", Chance = "0" },
        ["Minty"] = { PriceMultiply = "2.2", Color = "0.501961, 1, 0.72549", Chance = "0" },
        ["Electric"] = { PriceMultiply = "1.45", Color = "1, 0.960784, 0.388235", Chance = "15" },
        ["Unsellable"] = { PriceMultiply = "0", Color = "1, 0.298039, 0.298039", Chance = "0" },
        ["Atlantean"] = { PriceMultiply = "3", Color = "0.133333, 0.6, 0.584314", Chance = "0" },
        ["Glossy"] = { PriceMultiply = "1.6", Color = "0.572549, 0.886275, 1", Chance = "25" },
        ["Hexed"] = { PriceMultiply = "1.5", Color = "0.65098, 0, 0", Chance = "15" },
        ["Midas"] = { PriceMultiply = "2", Color = "1, 0.603922, 0.278431", Chance = "3" },
        ["Translucent"] = { PriceMultiply = "1.3", Color = "0.529412, 1, 0.74902", Chance = "20" },
        ["Sinister"] = { PriceMultiply = "1.9", Color = "0.784314, 0.345098, 0.172549", Chance = "0" },
        ["Lunar"] = { PriceMultiply = "2.5", Color = "0.741176, 0.662745, 1", Chance = "20" },
        ["Nuclear"] = { PriceMultiply = "4", Color = "0, 1, 0", Chance = "0" },
        ["Purified"] = { PriceMultiply = "2", Color = "0.431373, 1, 0.470588", Chance = "0" },
        ["Seasonal"] = { PriceMultiply = "1.3", Color = "0.882353, 0.145098, 0.145098", Chance = "0" },
        ["Festive"] = { PriceMultiply = "1.4", Color = "1, 0.486275, 0.486275", Chance = "0" },
        ["Crystalized"] = { PriceMultiply = "1.75", Color = "1, 0.447059, 0.0784314", Chance = "0" },
        ["Aurulent"] = { PriceMultiply = "5", Color = "0.635294, 0.360784, 0.0235294", Chance = "0" },
        ["Revitalized"] = { PriceMultiply = "4", Color = "0.643137, 1, 0.666667", Chance = "0" },
        ["Aurelian"] = { PriceMultiply = "3", Color = "0.564706, 0.152941, 0.027451", Chance = "0" },
        ["Sunken"] = { PriceMultiply = "4", Color = "0.0901961, 0.364706, 1", Chance = "0" },
        ["Heavenly"] = { PriceMultiply = "5", Color = "1, 0.972549, 0.772549", Chance = "0" },
        ["Aureolin"] = { PriceMultiply = "5", Color = "0.862745, 0.603922, 0.00392157", Chance = "0" },
        ["Negative"] = { PriceMultiply = "1.3", Color = "0.458824, 0.403922, 0.886275", Chance = "30" },
        ["Sleet"] = { PriceMultiply = "2.4", Color = "0.262745, 0.298039, 0.415686", Chance = "0" },
        ["Solarblaze"] = { PriceMultiply = "2.5", Color = "1, 0.415686, 0", Chance = "0" },
        ["Greedy"] = { PriceMultiply = "4", Color = "1, 0.760784, 0.14902", Chance = "1.5" },
        ["Ghastly"] = { PriceMultiply = "2", Color = "0.380392, 1, 0.368627", Chance = "0" },
    },
    Fish = {
        ["Sand Dollar"] = { Price = "20", Rarity = "Common", WeightPool = {1, 2}, From = "Ocean" },
        ["Snowcap Algae"] = { Price = "50", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Icicle"] = { Price = "130", Rarity = "Limited", WeightPool = {4, 12}, From = "N/A" },
        ["Lingcod"] = { Price = "110", Rarity = "Unusual", WeightPool = {40, 140}, From = "Snowcap" },
        ["Deep Sea Fragment"] = { Price = "0", Rarity = "Fragment", WeightPool = {1, 1}, From = "Ancient Isle" },
        ["Small Spine Chimera"] = { Price = "1200", Rarity = "Legendary", WeightPool = {800, 1500}, From = "The Depths" },
        ["Seaweed"] = { Price = "9", Rarity = "Trash", WeightPool = {1, 3}, From = "None" },
        ["Napoleonfish"] = { Price = "200", Rarity = "Rare", WeightPool = {250, 350}, From = "Sunstone" },
        ["Frozen Fangfish"] = { Price = "650", Rarity = "Legendary", WeightPool = {50, 80}, From = "Winter's Edge" },
        ["Midnight Axolotl"] = { Price = "1100", Rarity = "Legendary", WeightPool = {10, 30}, From = "Desolate Deep" },
        ["Trout"] = { Price = "65", Rarity = "Common", WeightPool = {9, 50}, From = "Moosewood" },
        ["Rabbitfish"] = { Price = "1100", Rarity = "Legendary", WeightPool = {25, 60}, From = "Ocean" },
        ["Sailfish"] = { Price = "800", Rarity = "Rare", WeightPool = {400, 600}, From = "Ocean" },
        ["Captain's Goldfish"] = { Price = "1700", Rarity = "Mythical", WeightPool = {10, 25}, From = "Forsaken Shores" },
        ["Largemouth Bass"] = { Price = "85", Rarity = "Common", WeightPool = {10, 45}, From = "Moosewood" },
        ["Walleye"] = { Price = "90", Rarity = "Uncommon", WeightPool = {18, 40}, From = "Terrapin" },
        ["Countdown Perch"] = { Price = "2000", Rarity = "Limited", WeightPool = {3000, 5000}, From = "N/A" },
        ["Sturgeon"] = { Price = "300", Rarity = "Rare", WeightPool = {200, 800}, From = "Snowcap" },
        ["Arctic Char"] = { Price = "80", Rarity = "Uncommon", WeightPool = {20, 60}, From = "Snowcap" },
        ["Oarfish"] = { Price = "4000", Rarity = "Mythical", WeightPool = {1500, 2500}, From = "Ocean" },
        ["Lobster"] = { Price = "130", Rarity = "Unusual", WeightPool = {9, 28}, From = "Ocean" },
        ["Blackfish"] = { Price = "100", Rarity = "Uncommon", WeightPool = {5, 20}, From = "Snowcap" },
        ["Starfish"] = { Price = "110", Rarity = "Uncommon", WeightPool = {20, 70}, From = "Ancient Isle" },
        ["Pollock"] = { Price = "70", Rarity = "Common", WeightPool = {10, 50}, From = "Snowcap" },
        ["Mushgrove Algae"] = { Price = "50", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Ancient Serpent Skull"] = { Price = "1200", Rarity = "Limited", WeightPool = {50, 100}, From = "N/A" },
        ["Moon Wood"] = { Price = "450", Rarity = "Legendary", WeightPool = {1, 2}, From = "None" },
        ["Cod"] = { Price = "90", Rarity = "Uncommon", WeightPool = {20, 100}, From = "Ocean" },
        ["Icy Carp"] = { Price = "250", Rarity = "Unusual", WeightPool = {30, 70}, From = "Overgrowth Caves" },
        ["Swordfish"] = { Price = "850", Rarity = "Rare", WeightPool = {1000, 2500}, From = "Ocean" },
        ["Grand Reef Guardian"] = { Price = "7000", Rarity = "Mythical", WeightPool = {400, 800}, From = "Grand Reef" },
        ["Ornament Fish"] = { Price = "140", Rarity = "Limited", WeightPool = {3, 7}, From = "N/A" },
        ["Galleon Goliath"] = { Price = "190", Rarity = "Uncommon", WeightPool = {50, 200}, From = "Forsaken Shores" },
        ["Destroyed Fossil"] = { Price = "35", Rarity = "Trash", WeightPool = {10, 45}, From = "The Depths" },
        ["Palaeoniscus"] = { Price = "125", Rarity = "Unusual", WeightPool = {25, 700}, From = "Ancient Archives" },
        ["Lurkerfish"] = { Price = "1500", Rarity = "Limited", WeightPool = {5, 20}, From = "N/A" },
        ["Hallucigenia"] = { Price = "200", Rarity = "Rare", WeightPool = {30, 100}, From = "Ancient Isle" },
        ["Bone"] = { Price = "30", Rarity = "Trash", WeightPool = {10, 25}, From = "Brine Pool" },
        ["Mahi Mahi"] = { Price = "150", Rarity = "Rare", WeightPool = {70, 150}, From = "Sunstone" },
        ["Onychodus"] = { Price = "115", Rarity = "Uncommon", WeightPool = {1000, 1400}, From = "Ancient Isle" },
        ["Skipjack Tuna"] = { Price = "150", Rarity = "Unusual", WeightPool = {70, 160}, From = "Snowcap" },
        ["Helicoprion"] = { Price = "6000", Rarity = "Mythical", WeightPool = {2500, 4200}, From = "Ancient Isle" },
        ["Porgy"] = { Price = "90", Rarity = "Common", WeightPool = {5, 30}, From = "Ocean" },
        ["Buccaneer Barracuda"] = { Price = "250", Rarity = "Uncommon", WeightPool = {90, 250}, From = "Forsaken Shores" },
        ["Icy Walleye"] = { Price = "350", Rarity = "Unusual", WeightPool = {40, 90}, From = "Glacial Grotto" },
        ["Boot"] = { Price = "15", Rarity = "Trash", WeightPool = {12, 12}, From = "None" },
        ["Megalodon"] = { Price = "10000", Rarity = "Exotic", WeightPool = {500000, 670000}, From = "Ancient Isle" },
        ["Bluefin Tuna"] = { Price = "350", Rarity = "Rare", WeightPool = {1000, 2200}, From = "Ocean" },
        ["Long Pike"] = { Price = "18000", Rarity = "Secret", WeightPool = {12, 35}, From = "Ocean" },
        ["Yellow Energy Crystal"] = { Price = "0", Rarity = "Mythical", WeightPool = {25, 50}, From = "None" },
        ["Spectral Serpent"] = { Price = "9000", Rarity = "Mythical", WeightPool = {110000, 130000}, From = "Brine Pool" },
        ["Mackerel"] = { Price = "75", Rarity = "Common", WeightPool = {10, 40}, From = "Ocean" },
        ["Stingray"] = { Price = "230", Rarity = "Rare", WeightPool = {150, 300}, From = "Ocean" },
        ["Minnow"] = { Price = "45", Rarity = "Common", WeightPool = {1, 6}, From = "Roslit" },
        ["Polar Alligator"] = { Price = "3000", Rarity = "Legendary", WeightPool = {800, 1500}, From = "Frigid Cavern" },
        ["Olmdeer"] = { Price = "400", Rarity = "Limited", WeightPool = {1, 4}, From = "N/A" },
        ["Phanerorhynchus"] = { Price = "450", Rarity = "Rare", WeightPool = {600, 1400}, From = "Ancient Archives" },
        ["Mutated Shark"] = { Price = "3000", Rarity = "Mythical", WeightPool = {2000, 4000}, From = "The Depths" },
        ["Gudgeon"] = { Price = "40", Rarity = "Common", WeightPool = {1, 3}, From = "Terrapin" },
        ["Goblin Shark"] = { Price = "450", Rarity = "Rare", WeightPool = {200, 450}, From = "The Depths" },
        ["Coral Guard"] = { Price = "250", Rarity = "Uncommon", WeightPool = {40, 90}, From = "Grand Reef" },
        ["Golden Smallmouth Bass"] = { Price = "700", Rarity = "Legendary", WeightPool = {15, 45}, From = "Terrapin" },
        ["Reef Minnow"] = { Price = "85", Rarity = "Common", WeightPool = {1, 6}, From = "Grand Reef" },
        ["Horseshoe Crab"] = { Price = "25", Rarity = "Common", WeightPool = {40, 90}, From = "Desolate Deep" },
        ["Abyssacuda"] = { Price = "400", Rarity = "Rare", WeightPool = {55, 110}, From = "Vertigo" },
        ["Diplurus"] = { Price = "800", Rarity = "Legendary", WeightPool = {800, 1600}, From = "Ancient Archives" },
        ["Ancient Wood"] = { Price = "450", Rarity = "Legendary", WeightPool = {1, 2}, From = "None" },
        ["Cookie"] = { Price = "20", Rarity = "Limited", WeightPool = {1, 6}, From = "N/A" },
        ["Crab"] = { Price = "100", Rarity = "Uncommon", WeightPool = {6, 14}, From = "Ocean" },
        ["Solar Fragment"] = { Price = "50", Rarity = "Fragment", WeightPool = {1, 1}, From = "Ancient Isle" },
        ["Icy Goldfish"] = { Price = "800", Rarity = "Rare", WeightPool = {200, 400}, From = "Overgrowth Caves" },
        ["Glacial Sturgeon"] = { Price = "7000", Rarity = "Mythical", WeightPool = {2500, 5000}, From = "Cryogenic Canal" },
        ["Frostling Goby"] = { Price = "180", Rarity = "Uncommon", WeightPool = {12, 28}, From = "Glacial Grotto" },
        ["Three-eyed Fish"] = { Price = "200", Rarity = "Unusual", WeightPool = {20, 60}, From = "The Depths" },
        ["Snowflake Smelt"] = { Price = "180", Rarity = "Uncommon", WeightPool = {10, 20}, From = "Cryogenic Canal" },
        ["Log"] = { Price = "124", Rarity = "Trash", WeightPool = {45, 75}, From = "None" },
        ["Anglerfish"] = { Price = "230", Rarity = "Rare", WeightPool = {5, 20}, From = "Ocean" },
        ["Snook"] = { Price = "110", Rarity = "Unusual", WeightPool = {30, 70}, From = "Moosewood" },
        ["Tidal Pike"] = { Price = "1500", Rarity = "Limited", WeightPool = {1500, 2500}, From = "N/A" },
        ["Enchant Relic"] = { Price = "3500", Rarity = "Relic", WeightPool = {210, 210}, From = "None" },
        ["Whale Shark"] = { Price = "6500", Rarity = "Mythical", WeightPool = {80000, 100000}, From = "Ocean" },
        ["Turkey"] = { Price = "4000", Rarity = "Limited", WeightPool = {80, 300}, From = "N/A" },
        ["Salmon"] = { Price = "130", Rarity = "Uncommon", WeightPool = {40, 100}, From = "Ocean" },
        ["Glass Diamond"] = { Price = "1500", Rarity = "Mythical", WeightPool = {25, 50}, From = "Overgrowth Caves" },
        ["Glacier Swordfish"] = { Price = "1000", Rarity = "Rare", WeightPool = {200, 450}, From = "Glacial Grotto" },
        ["Gazerfish"] = { Price = "190", Rarity = "Common", WeightPool = {80, 140}, From = "Brine Pool" },
        ["Mustard"] = { Price = "19000", Rarity = "Secret", WeightPool = {10, 40}, From = "Ocean" },
        ["Cobia"] = { Price = "230", Rarity = "Rare", WeightPool = {400, 700}, From = "Ancient Isle" },
        ["Confetti Shark"] = { Price = "1200", Rarity = "Limited", WeightPool = {800, 1200}, From = "N/A" },
        ["Crystal Wrasse"] = { Price = "450", Rarity = "Unusual", WeightPool = {40, 90}, From = "Grand Reef" },
        ["Hollyscale Trout"] = { Price = "150", Rarity = "Unusual", WeightPool = {5, 10}, From = "Winter's Edge" },
        ["Magma Tang"] = { Price = "130", Rarity = "Uncommon", WeightPool = {6, 30}, From = "Roslit Volcano" },
        ["Redeye Bass"] = { Price = "115", Rarity = "Unusual", WeightPool = {3, 15}, From = "Terrapin" },
        ["Carp"] = { Price = "110", Rarity = "Uncommon", WeightPool = {10, 50}, From = "Moosewood" },
        ["Hyneria"] = { Price = "145", Rarity = "Unusual", WeightPool = {10000, 18000}, From = "Ancient Isle" },
        ["Ghoulfish"] = { Price = "1000", Rarity = "Limited", WeightPool = {45, 120}, From = "N/A" },
        ["Mosasaurus"] = { Price = "7500", Rarity = "Mythical", WeightPool = {90000, 140000}, From = "Ancient Isle" },
        ["Hollow Flake Catfish"] = { Price = "450", Rarity = "Rare", WeightPool = {20, 50}, From = "Winter's Edge" },
        ["Icebreaker Haddock"] = { Price = "800", Rarity = "Rare", WeightPool = {200, 400}, From = "Cryogenic Canal" },
        ["Sea Snake"] = { Price = "5000", Rarity = "Mythical", WeightPool = {300, 800}, From = "The Depths" },
        ["Cursed Eel"] = { Price = "700", Rarity = "Rare", WeightPool = {80, 250}, From = "Forsaken Shores" },
        ["Grayling"] = { Price = "80", Rarity = "Common", WeightPool = {5, 20}, From = "Snowcap" },
        ["Lapis Lazuli"] = { Price = "700", Rarity = "Gemstone", WeightPool = {4, 14}, From = "Ancient Isle" },
        ["Dumbo Octopus"] = { Price = "900", Rarity = "Legendary", WeightPool = {15, 40}, From = "Roslit" },
        ["Mythic Fish"] = { Price = "2000", Rarity = "Mythical", WeightPool = {6, 14}, From = "Ocean" },
        ["Sardine"] = { Price = "30", Rarity = "Common", WeightPool = {1, 3}, From = "Ocean" },
        ["Lapisjack"] = { Price = "115", Rarity = "Rare", WeightPool = {200, 400}, From = "Keepers Altar" },
        ["Mullet"] = { Price = "90", Rarity = "Common", WeightPool = {5, 20}, From = "Ocean" },
        ["Whisker Bill"] = { Price = "3100", Rarity = "Mythical", WeightPool = {350, 1000}, From = "Moosewood" },
        ["Burbot"] = { Price = "80", Rarity = "Uncommon", WeightPool = {10, 35}, From = "Snowcap" },
        ["Snowback Char"] = { Price = "320", Rarity = "Unusual", WeightPool = {35, 75}, From = "Cryogenic Canal" },
        ["Rarities"] = { Price = "N/A", Rarity = "N/A", WeightPool = {}, From = "N/A" },
        ["Fish Barrel"] = { Price = "80", Rarity = "Uncommon", WeightPool = {150, 150}, From = "None" },
        ["Flying Fish"] = { Price = "1200", Rarity = "Legendary", WeightPool = {15, 50}, From = "Ocean" },
        ["Coral Geode"] = { Price = "200", Rarity = "Uncommon", WeightPool = {180, 180}, From = "Desolate Deep" },
        ["Amberjack"] = { Price = "115", Rarity = "Uncommon", WeightPool = {200, 400}, From = "Ocean" },
        ["Alligator Gar"] = { Price = "220", Rarity = "Rare", WeightPool = {200, 450}, From = "Roslit" },
        ["Xiphactinus"] = { Price = "170", Rarity = "Unusual", WeightPool = {1400, 2000}, From = "Ancient Isle" },
        ["Yellowfin Tuna"] = { Price = "120", Rarity = "Uncommon", WeightPool = {450, 1360}, From = "Moosewood" },
        ["Scurvy Sailfish"] = { Price = "300", Rarity = "Unusual", WeightPool = {150, 700}, From = "Forsaken Shores" },
        ["Mauve Pearl"] = { Price = "200", Rarity = "Rare", WeightPool = {1, 4}, From = "Roslit" },
        ["Barracuda's Spine"] = { Price = "50", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Emperor Jellyfish"] = { Price = "6000", Rarity = "Mythical", WeightPool = {5000, 8000}, From = "Desolate Deep" },
        ["Angelfish"] = { Price = "120", Rarity = "Unusual", WeightPool = {5, 20}, From = "Roslit" },
        ["Hourglass Bass"] = { Price = "3000", Rarity = "Limited", WeightPool = {8000, 12000}, From = "N/A" },
        ["Ruby"] = { Price = "200", Rarity = "Gemstone", WeightPool = {7, 20}, From = "Ancient Isle" },
        ["Earth Fragment"] = { Price = "0", Rarity = "Fragment", WeightPool = {1, 1}, From = "Ancient Isle" },
        ["Smallmouth Bass"] = { Price = "70", Rarity = "Common", WeightPool = {5, 17}, From = "Terrapin" },
        ["Shark Fang"] = { Price = "135", Rarity = "Limited", WeightPool = {30, 50}, From = "N/A" },
        ["Red Energy Crystal"] = { Price = "0", Rarity = "Mythical", WeightPool = {25, 50}, From = "None" },
        ["Bluefish"] = { Price = "65", Rarity = "Unusual", WeightPool = {4, 9}, From = "Keepers Altar" },
        ["Crystal Carp"] = { Price = "375", Rarity = "Unusual", WeightPool = {10, 18}, From = "Winter's Edge" },
        ["Swamp Bass"] = { Price = "60", Rarity = "Common", WeightPool = {20, 60}, From = "Mushgrove" },
        ["Chillback Whitefish"] = { Price = "280", Rarity = "Unusual", WeightPool = {25, 55}, From = "Glacial Grotto" },
        ["Trumpetfish"] = { Price = "100", Rarity = "Unusual", WeightPool = {9, 20}, From = "Sunstone" },
        ["Sawfish"] = { Price = "1500", Rarity = "Legendary", WeightPool = {4000, 6000}, From = "Ocean" },
        ["Rock"] = { Price = "15", Rarity = "Trash", WeightPool = {150, 210}, From = "None" },
        ["Mussel"] = { Price = "20", Rarity = "Common", WeightPool = {1, 2}, From = "Ocean" },
        ["Common Crate"] = { Price = "80", Rarity = "Uncommon", WeightPool = {80, 80}, From = "None" },
        ["Golden Seahorse"] = { Price = "2900", Rarity = "Mythical", WeightPool = {3, 8}, From = "Forsaken Shores" },
        ["Bluegill"] = { Price = "60", Rarity = "Common", WeightPool = {1, 6}, From = "Snowcap" },
        ["Ice Anchovy"] = { Price = "140", Rarity = "Uncommon", WeightPool = {2, 6}, From = "Overgrowth Caves" },
        ["Ice Octopus"] = { Price = "350", Rarity = "Unusual", WeightPool = {30, 80}, From = "Frigid Cavern" },
        ["Globe Jellyfish"] = { Price = "300", Rarity = "Unusual", WeightPool = {140, 240}, From = "Brine Pool" },
        ["Iced Perch"] = { Price = "250", Rarity = "Unusual", WeightPool = {20, 45}, From = "Cryogenic Canal" },
        ["Spider Crab"] = { Price = "550", Rarity = "Rare", WeightPool = {80, 250}, From = "The Depths" },
        ["Meg's Spine"] = { Price = "1500", Rarity = "Mythical", WeightPool = {25, 50}, From = "None" },
        ["Frost Minnow"] = { Price = "150", Rarity = "Uncommon", WeightPool = {8, 16}, From = "Cryogenic Canal" },
        ["Chinfish"] = { Price = "85", Rarity = "Uncommon", WeightPool = {20, 40}, From = "Sunstone" },
        ["Twilight Eel"] = { Price = "90", Rarity = "Uncommon", WeightPool = {100, 200}, From = "Vertigo" },
        ["Prawn"] = { Price = "45", Rarity = "Uncommon", WeightPool = {1, 5}, From = "Ocean" },
        ["Phantom Megalodon"] = { Price = "20000", Rarity = "Limited", WeightPool = {500000, 670000}, From = "Ancient Isle" },
        ["Icy Tuna"] = { Price = "600", Rarity = "Rare", WeightPool = {100, 250}, From = "Overgrowth Caves" },
        ["The Depths Key"] = { Price = "800", Rarity = "Exotic", WeightPool = {500, 1000}, From = "Vertigo" },
        ["Quality Bait Crate"] = { Price = "150", Rarity = "Rare", WeightPool = {120, 120}, From = "None" },
        ["Ice Jellyfish"] = { Price = "280", Rarity = "Unusual", WeightPool = {20, 45}, From = "Frigid Cavern" },
        ["King Oyster"] = { Price = "200", Rarity = "Rare", WeightPool = {4, 10}, From = "Terrapin" },
        ["Sea Turtle"] = { Price = "2000", Rarity = "Mythical", WeightPool = {700, 1500}, From = "Terrapin" },
        ["Icebeard Shark"] = { Price = "8000", Rarity = "Mythical", WeightPool = {3000, 6000}, From = "Glacial Grotto" },
        ["Ancient Megalodon"] = { Price = "16000", Rarity = "Exotic", WeightPool = {500000, 700000}, From = "Ancient Isle" },
        ["Nautilus"] = { Price = "1000", Rarity = "Legendary", WeightPool = {400, 800}, From = "The Depths" },
        ["Ancient Eel"] = { Price = "1500", Rarity = "Legendary", WeightPool = {1000, 2000}, From = "The Depths" },
        ["Driftwood"] = { Price = "10", Rarity = "Trash", WeightPool = {6, 6}, From = "None" },
        ["Black Dragon Fish"] = { Price = "500", Rarity = "Rare", WeightPool = {150, 400}, From = "The Depths" },
        ["Pumpkinseed"] = { Price = "90", Rarity = "Uncommon", WeightPool = {1, 5}, From = "Roslit" },
        ["Whiptail Catfish"] = { Price = "600", Rarity = "Legendary", WeightPool = {10, 30}, From = "Moosewood" },
        ["Ice"] = { Price = "15", Rarity = "Trash", WeightPool = {40, 60}, From = "Snowcap" },
        ["Barracuda"] = { Price = "150", Rarity = "Uncommon", WeightPool = {55, 110}, From = "Ocean" },
        ["Snowfish"] = { Price = "800", Rarity = "Rare", WeightPool = {200, 450}, From = "Frigid Cavern" },
        ["Corsair Grouper"] = { Price = "35", Rarity = "Common", WeightPool = {50, 200}, From = "Forsaken Shores" },
        ["Glacier Glowfish"] = { Price = "1800", Rarity = "Mythical", WeightPool = {80, 150}, From = "Winter's Edge" },
        ["Ginsu Shark"] = { Price = "3000", Rarity = "Legendary", WeightPool = {7800, 10000}, From = "Ancient Isle" },
        ["Stalactite"] = { Price = "35", Rarity = "Trash", WeightPool = {60, 130}, From = "Desolate Deep" },
        ["Shipwreck Barracuda"] = { Price = "1200", Rarity = "Legendary", WeightPool = {100, 300}, From = "Forsaken Shores" },
        ["Frozen Walnut"] = { Price = "2500", Rarity = "Mythical", WeightPool = {500, 1000}, From = "Overgrowth Caves" },
        ["Axolotl"] = { Price = "1000", Rarity = "Legendary", WeightPool = {5, 15}, From = "Roslit" },
        ["Supreme Present"] = { Price = "650", Rarity = "Limited", WeightPool = {90, 90}, From = "N/A" },
        ["Reef Parrotfish"] = { Price = "900", Rarity = "Rare", WeightPool = {70, 200}, From = "Grand Reef" },
        ["Forsaken Algae"] = { Price = "50", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Ancient Serpent Spine"] = { Price = "800", Rarity = "Limited", WeightPool = {30, 80}, From = "N/A" },
        ["Meg's Fang"] = { Price = "1500", Rarity = "Mythical", WeightPool = {10, 20}, From = "None" },
        ["Swamp Scallop"] = { Price = "150", Rarity = "Unusual", WeightPool = {6, 14}, From = "Mushgrove" },
        ["Goldfish"] = { Price = "65", Rarity = "Uncommon", WeightPool = {2, 7}, From = "Moosewood" },
        ["Exalted Relic"] = { Price = "12000", Rarity = "Relic", WeightPool = {210, 210}, From = "None" },
        ["Icy Salmon"] = { Price = "180", Rarity = "Uncommon", WeightPool = {40, 100}, From = "Overgrowth Caves" },
        ["Colossal Squid"] = { Price = "6500", Rarity = "Mythical", WeightPool = {7000, 12000}, From = "Ocean" },
        ["Cockatoo Squid"] = { Price = "200", Rarity = "Unusual", WeightPool = {4, 20}, From = "Desolate Deep" },
        ["Mushgrove Crab"] = { Price = "330", Rarity = "Rare", WeightPool = {6, 14}, From = "Mushgrove" },
        ["Zombiefish"] = { Price = "200", Rarity = "Limited", WeightPool = {15, 30}, From = "N/A" },
        ["Acanthodii"] = { Price = "160", Rarity = "Unusual", WeightPool = {130, 160}, From = "Ancient Isle" },
        ["Phantom Ray"] = { Price = "140", Rarity = "Uncommon", WeightPool = {40, 60}, From = "Desolate Deep" },
        ["Banana"] = { Price = "18500", Rarity = "Secret", WeightPool = {4, 10}, From = "Ancient Isle" },
        ["Frigid Taco"] = { Price = "600", Rarity = "Rare", WeightPool = {100, 250}, From = "Frigid Cavern" },
        ["Pale Tang"] = { Price = "100", Rarity = "Uncommon", WeightPool = {3, 15}, From = "Keepers Altar" },
        ["Frozen Pike"] = { Price = "650", Rarity = "Rare", WeightPool = {100, 250}, From = "Cryogenic Canal" },
        ["Lepidotes"] = { Price = "1800", Rarity = "Mythical", WeightPool = {900, 2000}, From = "Ancient Archives" },
        ["Molten Banshee"] = { Price = "6500", Rarity = "Exotic", WeightPool = {3000, 5500}, From = "Roslit Volcano" },
        ["RarityColours"] = { Price = "N/A", Rarity = "N/A", WeightPool = {}, From = "N/A" },
        ["Reef Goby"] = { Price = "200", Rarity = "Uncommon", WeightPool = {10, 30}, From = "Grand Reef" },
        ["Candy Fish"] = { Price = "200", Rarity = "Limited", WeightPool = {5, 10}, From = "N/A" },
        ["Dweller Catfish"] = { Price = "440", Rarity = "Rare", WeightPool = {100, 160}, From = "Brine Pool" },
        ["Aurora Trout"] = { Price = "6000", Rarity = "Mythical", WeightPool = {2000, 4000}, From = "Cryogenic Canal" },
        ["Eel"] = { Price = "130", Rarity = "Unusual", WeightPool = {8, 45}, From = "Moosewood" },
        ["Spiderfish"] = { Price = "30", Rarity = "Common", WeightPool = {3, 10}, From = "Vertigo" },
        ["Butterflyfish"] = { Price = "110", Rarity = "Uncommon", WeightPool = {2, 15}, From = "Roslit" },
        ["Eyefestation"] = { Price = "3000", Rarity = "Legendary", WeightPool = {4800, 6500}, From = "N/A" },
        ["Santa Salmon"] = { Price = "120", Rarity = "Limited", WeightPool = {80, 200}, From = "N/A" },
        ["Gingerbread Fish"] = { Price = "135", Rarity = "Limited", WeightPool = {20, 35}, From = "N/A" },
        ["Barreleye Fish"] = { Price = "4500", Rarity = "Mythical", WeightPool = {50, 150}, From = "The Depths" },
        ["Carbon Crate"] = { Price = "140", Rarity = "Rare", WeightPool = {160, 160}, From = "None" },
        ["Coral Chromis"] = { Price = "120", Rarity = "Common", WeightPool = {5, 20}, From = "Grand Reef" },
        ["Inferno Wood"] = { Price = "700", Rarity = "Mythical", WeightPool = {1, 2}, From = "None" },
        ["Banditfish"] = { Price = "250", Rarity = "Rare", WeightPool = {150, 200}, From = "Desolate Deep" },
        ["Night Shrimp"] = { Price = "55", Rarity = "Common", WeightPool = {1, 2}, From = "Vertigo" },
        ["Nessie's Spine"] = { Price = "250", Rarity = "Limited", WeightPool = {40, 80}, From = "N/A" },
        ["Glass of Milk"] = { Price = "20", Rarity = "Limited", WeightPool = {1, 6}, From = "N/A" },
        ["Ribbon Eel"] = { Price = "150", Rarity = "Unusual", WeightPool = {5, 150}, From = "Roslit" },
        ["Clam"] = { Price = "13", Rarity = "Unusual", WeightPool = {9, 10}, From = "Roslit" },
        ["Brine Shrimp"] = { Price = "230", Rarity = "Uncommon", WeightPool = {1, 3}, From = "Brine Pool" },
        ["Green Energy Crystal"] = { Price = "0", Rarity = "Mythical", WeightPool = {25, 50}, From = "None" },
        ["Chillfin Herring"] = { Price = "450", Rarity = "Rare", WeightPool = {30, 70}, From = "Cryogenic Canal" },
        ["Frostbite Flounder"] = { Price = "750", Rarity = "Rare", WeightPool = {150, 300}, From = "Glacial Grotto" },
        ["Frigid Antlers"] = { Price = "1200", Rarity = "Legendary", WeightPool = {500, 1000}, From = "Overgrowth Caves" },
        ["Fossil Fan"] = { Price = "60", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Umbral Shark"] = { Price = "1000", Rarity = "Legendary", WeightPool = {1050, 1550}, From = "Keepers Altar" },
        ["Red Snapper"] = { Price = "70", Rarity = "Common", WeightPool = {10, 70}, From = "Moosewood" },
        ["Anchovy"] = { Price = "30", Rarity = "Common", WeightPool = {1, 3}, From = "Moosewood" },
        ["Bream"] = { Price = "60", Rarity = "Common", WeightPool = {11, 27}, From = "Moosewood" },
        ["Chinook Salmon"] = { Price = "230", Rarity = "Unusual", WeightPool = {100, 400}, From = "Terrapin" },
        ["Spine Bone"] = { Price = "80", Rarity = "Limited", WeightPool = {30, 60}, From = "N/A" },
        ["Birgeria"] = { Price = "200", Rarity = "Unusual", WeightPool = {500, 1200}, From = "Ancient Archives" },
        ["Festive Bait Crate"] = { Price = "500", Rarity = "Limited", WeightPool = {80, 80}, From = "N/A" },
        ["Longtail Bass"] = { Price = "120", Rarity = "Uncommon", WeightPool = {20, 40}, From = "Sunstone" },
        ["Frilled Shark"] = { Price = "150", Rarity = "Unusual", WeightPool = {40, 90}, From = "The Depths" },
        ["Rockstar Hermit Crab"] = { Price = "65", Rarity = "Unusual", WeightPool = {4, 12}, From = "Desolate Deep" },
        ["Flounder"] = { Price = "120", Rarity = "Unusual", WeightPool = {15, 55}, From = "Moosewood" },
        ["Ringle"] = { Price = "900", Rarity = "Mythical", WeightPool = {1, 4}, From = "Snowcap" },
        ["Icefang Barracuda"] = { Price = "650", Rarity = "Rare", WeightPool = {200, 450}, From = "Glacial Grotto" },
        ["Manta Ray"] = { Price = "3000", Rarity = "Mythical", WeightPool = {7750, 10000}, From = "Roslit" },
        ["Oyster"] = { Price = "30", Rarity = "Uncommon", WeightPool = {2, 5}, From = "Ocean" },
        ["White Perch"] = { Price = "80", Rarity = "Common", WeightPool = {2, 12}, From = "Mushgrove" },
        ["Barbed Shark"] = { Price = "8300", Rarity = "Legendary", WeightPool = {7000, 9500}, From = "Desolate Deep" },
        ["Scallop"] = { Price = "100", Rarity = "Uncommon", WeightPool = {2, 5}, From = "Ocean" },
        ["Cladoselache"] = { Price = "90", Rarity = "Common", WeightPool = {180, 240}, From = "Ancient Isle" },
        ["Piranha"] = { Price = "85", Rarity = "Common", WeightPool = {20, 50}, From = "Ancient Isle" },
        ["Deep-sea Dragonfish"] = { Price = "45", Rarity = "Common", WeightPool = {8, 40}, From = "The Depths" },
        ["Luminescent Minnow"] = { Price = "120", Rarity = "Unusual", WeightPool = {2, 8}, From = "The Depths" },
        ["Frostjaw Cod"] = { Price = "2000", Rarity = "Legendary", WeightPool = {500, 1000}, From = "Cryogenic Canal" },
        ["Wiifish"] = { Price = "1200", Rarity = "Legendary", WeightPool = {200, 400}, From = "Sunstone" },
        ["Treble Bass"] = { Price = "4000", Rarity = "Exotic", WeightPool = {10, 45}, From = "Moosewood" },
        ["Bowfin"] = { Price = "100", Rarity = "Uncommon", WeightPool = {30, 60}, From = "Mushgrove" },
        ["Grey Carp"] = { Price = "120", Rarity = "Uncommon", WeightPool = {20, 70}, From = "Mushgrove" },
        ["Borealis Snapper"] = { Price = "3500", Rarity = "Legendary", WeightPool = {800, 1600}, From = "Glacial Grotto" },
        ["Obsidian Salmon"] = { Price = "600", Rarity = "Legendary", WeightPool = {40, 180}, From = "Roslit Volcano" },
        ["Slate Tuna"] = { Price = "70", Rarity = "Common", WeightPool = {300, 600}, From = "Desolate Deep" },
        ["Catfish"] = { Price = "300", Rarity = "Rare", WeightPool = {50, 150}, From = "Mushgrove" },
        ["Alligator"] = { Price = "700", Rarity = "Legendary", WeightPool = {1500, 3000}, From = "Mushgrove" },
        ["Floppy"] = { Price = "2000", Rarity = "Legendary", WeightPool = {80, 100}, From = "Ancient Isle" },
        ["Sea Bass"] = { Price = "95", Rarity = "Common", WeightPool = {20, 60}, From = "Ocean" },
        ["Dunkleosteus"] = { Price = "3500", Rarity = "Legendary", WeightPool = {12000, 30000}, From = "Ancient Isle" },
        ["Ember Snapper"] = { Price = "200", Rarity = "Unusual", WeightPool = {60, 120}, From = "Roslit Volcano" },
        ["Dolphin"] = { Price = "1200", Rarity = "Legendary", WeightPool = {1500, 2000}, From = "Ocean" },
        ["Shrimp"] = { Price = "45", Rarity = "Common", WeightPool = {1, 2}, From = "Ocean" },
        ["White Bass"] = { Price = "110", Rarity = "Uncommon", WeightPool = {3, 25}, From = "Terrapin" },
        ["Santa Pufferfish"] = { Price = "2000", Rarity = "Limited", WeightPool = {8, 25}, From = "N/A" },
        ["Yellow Boxfish"] = { Price = "140", Rarity = "Unusual", WeightPool = {5, 20}, From = "Roslit" },
        ["Gilded Pearl"] = { Price = "120", Rarity = "Unusual", WeightPool = {1, 4}, From = "Roslit" },
        ["Nurse Shark"] = { Price = "200", Rarity = "Unusual", WeightPool = {1000, 1500}, From = "Ocean" },
        ["Shortfin Mako Shark"] = { Price = "190", Rarity = "Common", WeightPool = {250, 1000}, From = "Forsaken Shores" },
        ["Coelacanth"] = { Price = "370", Rarity = "Rare", WeightPool = {70, 100}, From = "Ocean" },
        ["Spined Fin"] = { Price = "300", Rarity = "Limited", WeightPool = {20, 50}, From = "N/A" },
        ["Chub"] = { Price = "40", Rarity = "Common", WeightPool = {10, 30}, From = "Roslit" },
        ["Amethyst"] = { Price = "150", Rarity = "Gemstone", WeightPool = {8, 16}, From = "Ancient Isle" },
        ["Bait Crate"] = { Price = "75", Rarity = "Uncommon", WeightPool = {80, 80}, From = "None" },
        ["Sea Urchin"] = { Price = "320", Rarity = "Rare", WeightPool = {2, 9}, From = "Ocean" },
        ["Cutlass Fish"] = { Price = "500", Rarity = "Unusual", WeightPool = {80, 250}, From = "Forsaken Shores" },
        ["Tire"] = { Price = "20", Rarity = "Trash", WeightPool = {110, 110}, From = "None" },
        ["Fangborn Gar"] = { Price = "170", Rarity = "Unusual", WeightPool = {170, 380}, From = "Vertigo" },
        ["Obsidian Swordfish"] = { Price = "2500", Rarity = "Mythical", WeightPool = {1000, 2500}, From = "Roslit Volcano" },
        ["Opal"] = { Price = "500", Rarity = "Gemstone", WeightPool = {9, 32}, From = "Ancient Isle" },
        ["Great Hammerhead Shark"] = { Price = "5500", Rarity = "Mythical", WeightPool = {2300, 5000}, From = "Ocean" },
        ["Basic Present"] = { Price = "120", Rarity = "Limited", WeightPool = {90, 90}, From = "N/A" },
        ["Pufferfish"] = { Price = "230", Rarity = "Rare", WeightPool = {5, 20}, From = "Ocean" },
        ["Ember Perch"] = { Price = "160", Rarity = "Unusual", WeightPool = {4, 15}, From = "Roslit Volcano" },
        ["Perch"] = { Price = "70", Rarity = "Common", WeightPool = {2, 12}, From = "Roslit" },
        ["Crown Bass"] = { Price = "1200", Rarity = "Legendary", WeightPool = {20, 60}, From = "Ocean" },
        ["Anomalocaris"] = { Price = "90", Rarity = "Uncommon", WeightPool = {100, 400}, From = "Ancient Isle" },
        ["Pike"] = { Price = "230", Rarity = "Unusual", WeightPool = {12, 35}, From = "Moosewood" },
        ["Pond Emperor"] = { Price = "900", Rarity = "Legendary", WeightPool = {1000, 2500}, From = "Snowcap" },
        ["Great White Shark"] = { Price = "6000", Rarity = "Mythical", WeightPool = {7000, 12000}, From = "Ocean" },
        ["Bull Shark"] = { Price = "400", Rarity = "Legendary", WeightPool = {900, 1300}, From = "Ocean" },
        ["Voltfish"] = { Price = "2200", Rarity = "Mythical", WeightPool = {8, 16}, From = "Sunstone" },
        ["Moonfish"] = { Price = "1800", Rarity = "Legendary", WeightPool = {2500, 5000}, From = "Ocean" },
        ["Sea Mine"] = { Price = "4000", Rarity = "Mythical", WeightPool = {2000, 3250}, From = "Desolate Deep" },
        ["Sockeye Salmon"] = { Price = "45", Rarity = "Common", WeightPool = {20, 70}, From = "Moosewood" },
        ["Basalt"] = { Price = "15", Rarity = "Trash", WeightPool = {150, 210}, From = "Roslit Volcano" },
        ["Pearl"] = { Price = "60", Rarity = "Common", WeightPool = {1, 4}, From = "Roslit" },
        ["Skelefish"] = { Price = "200", Rarity = "Limited", WeightPool = {5, 10}, From = "N/A" },
        ["Leedsichthys"] = { Price = "2200", Rarity = "Legendary", WeightPool = {9000, 11000}, From = "Ancient Isle" },
        ["Suckermouth Catfish"] = { Price = "160", Rarity = "Rare", WeightPool = {95, 170}, From = "Roslit" },
        ["Squid"] = { Price = "140", Rarity = "Unusual", WeightPool = {5, 25}, From = "Roslit" },
        ["Clownfish"] = { Price = "90", Rarity = "Uncommon", WeightPool = {1, 6}, From = "Roslit" },
        ["Blue Tang"] = { Price = "90", Rarity = "Uncommon", WeightPool = {3, 15}, From = "Roslit" },
        ["Glassfish"] = { Price = "45", Rarity = "Common", WeightPool = {1, 4}, From = "Sunstone" },
        ["Deep-sea Hatchetfish"] = { Price = "35", Rarity = "Common", WeightPool = {5, 35}, From = "The Depths" },
        ["Rose Pearl"] = { Price = "145", Rarity = "Unusual", WeightPool = {1, 4}, From = "Roslit" },
        ["Arapaima"] = { Price = "250", Rarity = "Rare", WeightPool = {1000, 2000}, From = "Roslit" },
        ["Halibut"] = { Price = "250", Rarity = "Rare", WeightPool = {1000, 2000}, From = "Ocean" },
        ["Deep Pearl"] = { Price = "880", Rarity = "Legendary", WeightPool = {1, 4}, From = "Roslit" },
        ["Aurora Pearl"] = { Price = "2250", Rarity = "Mythical", WeightPool = {1, 4}, From = "Roslit" },
        ["Olm"] = { Price = "900", Rarity = "Legendary", WeightPool = {1, 4}, From = "Terrapin" },
        ["Cookiecutter Shark"] = { Price = "500", Rarity = "Rare", WeightPool = {5, 15}, From = "Ocean" },
        ["Scrap Metal"] = { Price = "40", Rarity = "Trash", WeightPool = {10, 50}, From = "The Depths" },
        ["Haddock"] = { Price = "50", Rarity = "Common", WeightPool = {15, 40}, From = "Ocean" },
        ["Fungal Cluster"] = { Price = "9", Rarity = "Trash", WeightPool = {9, 9}, From = "Mushgrove" },
        ["Herring"] = { Price = "70", Rarity = "Common", WeightPool = {5, 11}, From = "Snowcap" },
        ["Sea Pickle"] = { Price = "2000", Rarity = "Mythical", WeightPool = {4, 10}, From = "Ocean" },
        ["Pyrogrub"] = { Price = "340", Rarity = "Rare", WeightPool = {300, 600}, From = "Roslit Volcano" },
        ["Sunfish"] = { Price = "1500", Rarity = "Legendary", WeightPool = {4000, 10000}, From = "Sunstone" },
        ["Moonstone"] = { Price = "1000", Rarity = "Gemstone", WeightPool = {5, 28}, From = "Ancient Isle" },
        ["Brine Phantom"] = { Price = "3000", Rarity = "Legendary", WeightPool = {4800, 6500}, From = "Brine Pool" },
        ["Frigid Mammoth Tusk"] = { Price = "3000", Rarity = "Mythical", WeightPool = {2500, 5000}, From = "Frigid Cavern" },
        ["Northstar Serpent"] = { Price = "20000", Rarity = "Limited", WeightPool = {140000, 200000}, From = "N/A" },
        ["Ancient Fragment"] = { Price = "500", Rarity = "Fragment", WeightPool = {1, 1}, From = "Ancient Isle" },
        ["Sweetfish"] = { Price = "40", Rarity = "Common", WeightPool = {2, 5}, From = "Sunstone" },
        ["Unique Present"] = { Price = "180", Rarity = "Limited", WeightPool = {90, 90}, From = "N/A" },
        ["Void Wood"] = { Price = "350", Rarity = "Legendary", WeightPool = {1, 2}, From = "None" },
        ["Red Tang"] = { Price = "100", Rarity = "Uncommon", WeightPool = {3, 15}, From = "Sunstone" },
        ["Candy Cane Carp"] = { Price = "75", Rarity = "Limited", WeightPool = {10, 50}, From = "N/A" },
        ["Ancient Algae"] = { Price = "50", Rarity = "Limited", WeightPool = {25, 50}, From = "N/A" },
        ["Depth Octopus"] = { Price = "175", Rarity = "Unusual", WeightPool = {30, 80}, From = "The Depths" },
        ["Claw Gill"] = { Price = "60", Rarity = "Limited", WeightPool = {15, 30}, From = "N/A" },
        ["Eternal Frostwhale"] = { Price = "12000", Rarity = "Limited", WeightPool = {10000, 15000}, From = "N/A" },
        ["Reefrunner Snapper"] = { Price = "750", Rarity = "Rare", WeightPool = {80, 250}, From = "Forsaken Shores" },
        ["Handfish"] = { Price = "1000", Rarity = "Mythical", WeightPool = {20, 60}, From = "Mushgrove" },
        ["Blue Energy Crystal"] = { Price = "0", Rarity = "Mythical", WeightPool = {25, 50}, From = "None" },
        ["Snowflake Flounder"] = { Price = "145", Rarity = "Limited", WeightPool = {15, 55}, From = "N/A" },
        ["Red Drum"] = { Price = "80", Rarity = "Common", WeightPool = {10, 25}, From = "Snowcap" },
        ["Snowgill Dace"] = { Price = "160", Rarity = "Uncommon", WeightPool = {10, 25}, From = "Glacial Grotto" },
        ["Frigid Crab"] = { Price = "300", Rarity = "Unusual", WeightPool = {15, 35}, From = "Overgrowth Caves" },
        ["Isonade"] = { Price = "8000", Rarity = "Mythical", WeightPool = {6000, 13000}, From = "Vertigo" },
        ["Frigid Shrimp"] = { Price = "175", Rarity = "Uncommon", WeightPool = {3, 8}, From = "Frigid Cavern" },
        ["Glacierfish"] = { Price = "800", Rarity = "Mythical", WeightPool = {400, 600}, From = "Snowcap" },
        ["Glacier Pike"] = { Price = "230", Rarity = "Unusual", WeightPool = {12, 35}, From = "Snowcap" },
        ["Ancient Depth Serpent"] = { Price = "8000", Rarity = "Exotic", WeightPool = {5000, 10000}, From = "The Depths" },
        ["Shiverfin Haddock"] = { Price = "500", Rarity = "Rare", WeightPool = {50, 120}, From = "Glacial Grotto" },
        ["Spine Blade"] = { Price = "100", Rarity = "Limited", WeightPool = {30, 60}, From = "N/A" },
        ["Volcanic Geode"] = { Price = "200", Rarity = "Rare", WeightPool = {200, 200}, From = "Roslit Volcano" },
        ["Golden Sea Pearl"] = { Price = "3500", Rarity = "Exotic", WeightPool = {1, 4}, From = "Roslit" },
        ["Rubber Ducky"] = { Price = "900", Rarity = "Legendary", WeightPool = {1, 7}, From = "Vertigo" },
        ["Marsh Gar"] = { Price = "280", Rarity = "Rare", WeightPool = {170, 380}, From = "Mushgrove" },
        ["Ice Eel"] = { Price = "155", Rarity = "Uncommon", WeightPool = {8, 20}, From = "Frigid Cavern" },
        ["Keepers Guardian"] = { Price = "250", Rarity = "Rare", WeightPool = {200, 400}, From = "Keepers Altar" },
        ["Voidfin Mahi"] = { Price = "450", Rarity = "Rare", WeightPool = {75, 155}, From = "Vertigo" },
        ["Nessie"] = { Price = "6500", Rarity = "Limited", WeightPool = {20000, 40000}, From = "N/A" },
        ["Amblypterus"] = { Price = "2500", Rarity = "Mythical", WeightPool = {700, 1800}, From = "Ancient Archives" },
        ["Coral Emperor"] = { Price = "4000", Rarity = "Legendary", WeightPool = {150, 300}, From = "Grand Reef" },
    },
    Bait = {
        ["Magnet"] = { LureSpeed = "0", Luck = "200", GenerelLuck = "0", Rarity = "Unusual", Resilience = "0", },
        ["Worm"] = { LureSpeed = "15", Luck = "25", GenerelLuck = "0", Rarity = "Common", Resilience = "0", },
        ["Peppermint Worm"] = { LureSpeed = "-5", Luck = "50", GenerelLuck = "30", Rarity = "Unusual", Resilience = "20", },
        ["Coal"] = { LureSpeed = "0", Luck = "45", GenerelLuck = "0", Rarity = "Rare", Resilience = "-10", },
        ["Squid"] = { LureSpeed = "-25", Luck = "55", GenerelLuck = "45", Rarity = "Unusual", Resilience = "0", },
        ["Fish Head"] = { LureSpeed = "10", Luck = "150", GenerelLuck = "0", Rarity = "Legendary", Resilience = "-10", },
        ["Insect"] = { LureSpeed = "5", Luck = "35", GenerelLuck = "0", Rarity = "Common", Resilience = "0", },
        ["Shrimp"] = { LureSpeed = "0", Luck = "45", GenerelLuck = "25", Rarity = "Uncommon", Resilience = "-5", },
        ["Bagel"] = { LureSpeed = "0", Luck = "25", GenerelLuck = "0", Rarity = "Common", Resilience = "15", },
        ["Super Flakes"] = { LureSpeed = "0", Luck = "0", GenerelLuck = "70", Rarity = "Rare", Resilience = "-15", },
        ["Seaweed"] = { LureSpeed = "20", Luck = "35", GenerelLuck = "0", Rarity = "Unusual", Resilience = "10", },
        ["Instant Catcher"] = { LureSpeed = "65", Luck = "0", GenerelLuck = "-20", Rarity = "Legendary", Resilience = "-15", },
        ["Night Shrimp"] = { LureSpeed = "15", Luck = "0", GenerelLuck = "90", Rarity = "Legendary", Resilience = "0", },
        ["Garbage"] = { LureSpeed = "-5", Luck = "0", GenerelLuck = "-250", Rarity = "Common", Resilience = "50", },
        ["Weird Algae"] = { LureSpeed = "-35", Luck = "0", GenerelLuck = "200", Rarity = "Legendary", Resilience = "0", },
        ["Shark Head"] = { LureSpeed = "-5", Luck = "225", GenerelLuck = "30", Rarity = "Mythical", Resilience = "10", },
        ["Holly Berry"] = { LureSpeed = "-5", Luck = "80", GenerelLuck = "30", Rarity = "Legendary", Resilience = "10", },
        ["Coral"] = { LureSpeed = "20", Luck = "0", GenerelLuck = "0", Rarity = "Unusual", Resilience = "20", },
        ["Maggot"] = { LureSpeed = "-10", Luck = "0", GenerelLuck = "35", Rarity = "Uncommon", Resilience = "0", },
        ["Deep Coral"] = { LureSpeed = "0", Luck = "-10", GenerelLuck = "0", Rarity = "Legendary", Resilience = "50", },
        ["Minnow"] = { LureSpeed = "0", Luck = "65", GenerelLuck = "0", Rarity = "Unusual", Resilience = "-10", },
        ["Rapid Catcher"] = { LureSpeed = "35", Luck = "0", GenerelLuck = "0", Rarity = "Rare", Resilience = "-15", },
        ["Aurora Bait"] = { LureSpeed = "-5", Luck = "100", GenerelLuck = "30", Rarity = "Mythical", Resilience = "10", },
        ["Flakes"] = { LureSpeed = "10", Luck = "55", GenerelLuck = "0", Rarity = "Common", Resilience = "-3", },
        ["Truffle Worm"] = { LureSpeed = "-10", Luck = "300", GenerelLuck = "0", Rarity = "Legendary", Resilience = "0", },
    },
    SkinCrates = {
        ["Ancient"] = { Price = "175000" },
        ["Desolate"] = { Price = "75000" },
        ["Moosewood"] = { Price = "25000" },
    },
    Codes = {
        ["NewYear"] = {},
        ["RFG"] = {},
    }
}
